# Generated by Django 2.1 on 2018-08-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='created on'),
        ),
    ]
